version: '3'
networks:
  my-network:
    driver: bridge
services:
  app:
    image: ansike/ansike:todo-v1
    #image: todo-v1
    # command: "sleep 3600"
    working_dir: /usr/src/app
    volumes:
      - ./usr/src/app:/app
    ports:
      - 4001:4001
    depends_on:
      - mysql
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: todopw
      MYSQL_DATABASE: todo_db
      TZ: Asia/Shanghai
    networks:
      - my-network
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: todopw
      MYSQL_DATABASE: todo_db
    volumes:
      # 数据挂载
      #- /root/mysql/data/:/var/lib/mysql/
      # 配置挂载
      #- /root/mysql/conf/:/etc/mysql/conf.d/
      # 初始化目录挂载，注意此处我只跑了这个挂载，只是为了说明其他配置不应该数据初始化
      - ./packages/node/src/todo.sql:/docker-entrypoint-initdb.d/todo.sql
    networks:
      - my-network
  redis:
    image: redis
    networks:
      - my-network

