version: '3'

services:
  app:
    image: node
    command: npm start
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
      MYSQL_USERNAME: todo_user
      MYSQL_PASSWORD: todopw
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
