FROM node:16.19.1-buster-slim as builder

WORKDIR /usr/src/app

COPY ./ ./

RUN set -x \
  && chmod +x ./shell/web.build.sh \
  && bash ./shell/web.build.sh \
  && chmod +x ./shell/node.build.sh \
  && bash ./shell/node.build.sh \
  && echo 'docker shell build completed'

FROM node:16.19.1-buster-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/output ./output

ENV NODE_ENV=production \
  PORT=4001

EXPOSE 4001

CMD cd output/packages/node && yarn start:prod
